const Words = {
    "japanese": {
      "hiragana": {
        "a": { self: "あ", translation: "A", falseStates: ["I", "U", "E"], id: 0 },
        "i": { self: "い", translation: "I", falseStates: ["A", "U", "E"], id: 1 },
        "u": { self: "う", translation: "U", falseStates: ["A", "I", "E"], id: 2 },
        "e": { self: "え", translation: "E", falseStates: ["A", "I", "U"], id: 3 },
        "o": { self: "お", translation: "O", falseStates: ["A", "I", "U"], id: 4 },
        "ka": { self: "か", translation: "Ka", falseStates: ["Ki", "Ku", "Ke"], id: 5 },
        "ki": { self: "き", translation: "Ki", falseStates: ["Ka", "Ku", "Ke"], id: 6 },
        "ku": { self: "く", translation: "Ku", falseStates: ["Ka", "Ki", "Ke"], id: 7 },
        "ke": { self: "け", translation: "Ke", falseStates: ["Ka", "Ki", "Ku"], id: 8 },
        "ko": { self: "こ", translation: "Ko", falseStates: ["Ka", "Ki", "Ku"], id: 9 },
        "sa": { self: "さ", translation: "Sa", falseStates: ["Shi", "Su", "Se"], id: 10 },
        "shi": { self: "し", translation: "Shi", falseStates: ["Sa", "Su", "Se"], id: 11 },
        "su": { self: "す", translation: "Su", falseStates: ["Sa", "Shi", "Se"], id: 12 },
        "se": { self: "せ", translation: "Se", falseStates: ["Sa", "Shi", "Su"], id: 13 },
        "so": { self: "そ", translation: "So", falseStates: ["Sa", "Shi", "Su"], id: 14 },
        "ta": { self: "た", translation: "Ta", falseStates: ["Chi", "Tsu", "Te"], id: 15 },
        "chi": { self: "ち", translation: "Chi", falseStates: ["Ta", "Tsu", "Te"], id: 16 },
        "tsu": { self: "つ", translation: "Tsu", falseStates: ["Ta", "Chi", "Te"], id: 17 },
        "te": { self: "て", translation: "Te", falseStates: ["Ta", "Chi", "Tsu"], id: 18 },
        "to": { self: "と", translation: "To", falseStates: ["Ta", "Chi", "Tsu"], id: 19 },
        "na": { self: "な", translation: "Na", falseStates: ["Ni", "Nu", "Ne"], id: 20 },
        "ni": { self: "に", translation: "Ni", falseStates: ["Na", "Nu", "Ne"], id: 21 },
        "nu": { self: "ぬ", translation: "Nu", falseStates: ["Na", "Ni", "Ne"], id: 22 },
        "ne": { self: "ね", translation: "Ne", falseStates: ["Na", "Ni", "Nu"], id: 23 },
        "no": { self: "の", translation: "No", falseStates: ["Na", "Ni", "Nu"], id: 24 },
        "ha": { self: "は", translation: "Ha", falseStates: ["Hi", "Fu", "He"], id: 25 },
        "hi": { self: "ひ", translation: "Hi", falseStates: ["Ha", "Fu", "He"], id: 26 },
        "fu": { self: "ふ", translation: "Fu", falseStates: ["Ha", "Hi", "He"], id: 27 },
        "he": { self: "へ", translation: "He", falseStates: ["Ha", "Hi", "Fu"], id: 28 },
        "ho": { self: "ほ", translation: "Ho", falseStates: ["Ha", "Hi", "Fu"], id: 29 },
        "ma": { self: "ま", translation: "Ma", falseStates: ["Mi", "Mu", "Me"], id: 30 },
        "mi": { self: "み", translation: "Mi", falseStates: ["Ma", "Mu", "Me"], id: 31 },
        "mu": { self: "む", translation: "Mu", falseStates: ["Ma", "Mi", "Me"], id: 32 },
        "me": { self: "め", translation: "Me", falseStates: ["Ma", "Mi", "Mu"], id: 33 },
        "mo": { self: "も", translation: "Mo", falseStates: ["Ma", "Mi", "Mu"], id: 34 },
        "ya": { self: "や", translation: "Ya", falseStates: ["Yu", "Yo"], id: 35 },
        "yu": { self: "ゆ", translation: "Yu", falseStates: ["Ya", "Yo"], id: 36 },
        "yo": { self: "よ", translation: "Yo", falseStates: ["Ya", "Yu"], id: 37 },
        "ra": { self: "ら", translation: "Ra", falseStates: ["Ri", "Ru", "Re"], id: 38 },
        "ri": { self: "り", translation: "Ri", falseStates: ["Ra", "Ru", "Re"], id: 39 },
        "ru": { self: "る", translation: "Ru", falseStates: ["Ra", "Ri", "Re"], id: 40 },
        "re": { self: "れ", translation: "Re", falseStates: ["Ra", "Ri", "Ru"], id: 41 },
        "ro": { self: "ろ", translation: "Ro", falseStates: ["Ra", "Ri", "Ru"], id: 42 },
        "wa": { self: "わ", translation: "Wa", falseStates: ["Wo", "N"], id: 43 },
        "wo": { self: "を", translation: "Wo", falseStates: ["Wa", "N"], id: 44 },
        "n": { self: "ん", translation: "N", falseStates: ["Wa", "Wo"], id: 45 },
        "ga": { self: "が", translation: "Ga", falseStates: ["Gi", "Gu", "Ge"], id: 46 },
        "gi": { self: "ぎ", translation: "Gi", falseStates: ["Ga", "Gu", "Ge"], id: 47 },
        "gu": { self: "ぐ", translation: "Gu", falseStates: ["Ga", "Gi", "Ge"], id: 48 },
        "ge": { self: "げ", translation: "Ge", falseStates: ["Ga", "Gi", "Gu"], id: 49 },
        "go": { self: "ご", translation: "Go", falseStates: ["Ga", "Gi", "Gu"], id: 50 },
        "za": { self: "ざ", translation: "Za", falseStates: ["Ji", "Zu", "Ze"], id: 51 },
        "ji": { self: "じ", translation: "Ji", falseStates: ["Za", "Zu", "Ze"], id: 52 },
        "zu": { self: "ず", translation: "Zu", falseStates: ["Za", "Ji", "Ze"], id: 53 },
        "ze": { self: "ぜ", translation: "Ze", falseStates: ["Za", "Ji", "Zu"], id: 54 },
        "zo": { self: "ぞ", translation: "Zo", falseStates: ["Za", "Ji", "Zu"], id: 55 },
        "da": { self: "だ", translation: "Da", falseStates: ["Di", "Du", "De"], id: 56 },
        "di": { self: "ぢ", translation: "Di", falseStates: ["Da", "Du", "De"], id: 57 },
        "du": { self: "づ", translation: "Du", falseStates: ["Da", "Di", "De"], id: 58 },
        "de": { self: "で", translation: "De", falseStates: ["Da", "Di", "Du"], id: 59 },
        "do": { self: "ど", translation: "Do", falseStates: ["Da", "Di", "Du"], id: 60 },
        "ba": { self: "ば", translation: "Ba", falseStates: ["Bi", "Bu", "Be"], id: 61 },
        "bi": { self: "び", translation: "Bi", falseStates: ["Ba", "Bu", "Be"], id: 62 },
        "bu": { self: "ぶ", translation: "Bu", falseStates: ["Ba", "Bi", "Be"], id: 63 },
        "be": { self: "べ", translation: "Be", falseStates: ["Ba", "Bi", "Bu"], id: 64 },
        "bo": { self: "ぼ", translation: "Bo", falseStates: ["Ba", "Bi", "Bu"], id: 65 },
        "pa": { self: "ぱ", translation: "Pa", falseStates: ["Pi", "Pu", "Pe"], id: 66 },
        "pi": { self: "ぴ", translation: "Pi", falseStates: ["Pa", "Pu", "Pe"], id: 67 },
        "pu": { self: "ぷ", translation: "Pu", falseStates: ["Pa", "Pi", "Pe"], id: 68 },
        "pe": { self: "ぺ", translation: "Pe", falseStates: ["Pa", "Pi", "Pu"], id: 69 },
        "po": { self: "ぽ", translation: "Po", falseStates: ["Pa", "Pi", "Pu"], id: 70 }
      },
      "katakana": {
        "a": { self: "ア", translation: "a", falseStates: ["i", "u", "e"], id: 0 },
        "i": { self: "イ", translation: "i", falseStates: ["a", "u", "e"], id: 1 },
        "u": { self: "ウ", translation: "u", falseStates: ["a", "i", "e"], id: 2 },
        "e": { self: "エ", translation: "e", falseStates: ["a", "i", "u"], id: 3 },
        "o": { self: "オ", translation: "o", falseStates: ["a", "i", "u"], id: 4 },
        "ka": { self: "カ", translation: "ka", falseStates: ["ki", "ku", "ke"], id: 5 },
        "ki": { self: "キ", translation: "ki", falseStates: ["ka", "ku", "ke"], id: 6 },
        "ku": { self: "ク", translation: "ku", falseStates: ["ka", "ki", "ke"], id: 7 },
        "ke": { self: "ケ", translation: "ke", falseStates: ["ka", "ki", "ku"], id: 8 },
        "ko": { self: "コ", translation: "ko", falseStates: ["ka", "ki", "ku"], id: 9 },
        "sa": { self: "サ", translation: "sa", falseStates: ["shi", "su", "se"], id: 10 },
        "shi": { self: "シ", translation: "shi", falseStates: ["sa", "su", "se"], id: 11 },
        "su": { self: "ス", translation: "su", falseStates: ["sa", "shi", "se"], id: 12 },
        "se": { self: "セ", translation: "se", falseStates: ["sa", "shi", "su"], id: 13 },
        "so": { self: "ソ", translation: "so", falseStates: ["sa", "shi", "su"], id: 14 },
        "ta": { self: "タ", translation: "ta", falseStates: ["chi", "tsu", "te"], id: 15 },
        "chi": { self: "チ", translation: "chi", falseStates: ["ta", "tsu", "te"], id: 16 },
        "tsu": { self: "ツ", translation: "tsu", falseStates: ["ta", "chi", "te"], id: 17 },
        "te": { self: "テ", translation: "te", falseStates: ["ta", "chi", "tsu"], id: 18 },
        "to": { self: "ト", translation: "to", falseStates: ["ta", "chi", "tsu"], id: 19 },
        "na": { self: "ナ", translation: "na", falseStates: ["ni", "nu", "ne"], id: 20 },
        "ni": { self: "ニ", translation: "ni", falseStates: ["na", "nu", "ne"], id: 21 },
        "nu": { self: "ヌ", translation: "nu", falseStates: ["na", "ni", "ne"], id: 22 },
        "ne": { self: "ネ", translation: "ne", falseStates: ["na", "ni", "nu"], id: 23 },
        "no": { self: "ノ", translation: "no", falseStates: ["na", "ni", "nu"], id: 24 },
        "ha": { self: "ハ", translation: "ha", falseStates: ["hi", "fu", "he"], id: 25 },
        "hi": { self: "ヒ", translation: "hi", falseStates: ["ha", "fu", "he"], id: 26 },
        "fu": { self: "フ", translation: "fu", falseStates: ["ha", "hi", "he"], id: 27 },
        "he": { self: "ヘ", translation: "he", falseStates: ["ha", "hi", "fu"], id: 28 },
        "ho": { self: "ホ", translation: "ho", falseStates: ["ha", "hi", "fu"], id: 29 },
        "ma": { self: "マ", translation: "ma", falseStates: ["mi", "mu", "me"], id: 30 },
        "mi": { self: "ミ", translation: "mi", falseStates: ["ma", "mu", "me"], id: 31 },
        "mu": { self: "ム", translation: "mu", falseStates: ["ma", "mi", "me"], id: 32 },
        "me": { self: "メ", translation: "me", falseStates: ["ma", "mi", "mu"], id: 33 },
        "mo": { self: "モ", translation: "mo", falseStates: ["ma", "mi", "mu"], id: 34 },
        "ya": { self: "ヤ", translation: "ya", falseStates: ["yu", "yo"], id: 35 },
        "yu": { self: "ユ", translation: "yu", falseStates: ["ya", "yo"], id: 36 },
        "yo": { self: "ヨ", translation: "yo", falseStates: ["ya", "yu"], id: 37 },
        "ra": { self: "ラ", translation: "ra", falseStates: ["ri", "ru", "re"], id: 38 },
        "ri": { self: "リ", translation: "ri", falseStates: ["ra", "ru", "re"], id: 39 },
        "ru": { self: "ル", translation: "ru", falseStates: ["ra", "ri", "re"], id: 40 },
        "re": { self: "レ", translation: "re", falseStates: ["ra", "ri", "ru"], id: 41 },
        "ro": { self: "ロ", translation: "ro", falseStates: ["ra", "ri", "ru"], id: 42 },
        "wa": { self: "ワ", translation: "wa", falseStates: ["wo", "n"], id: 43 },
        "wo": { self: "ヲ", translation: "wo", falseStates: ["wa", "n"], id: 44 },
        "n": { self: "ン", translation: "n", falseStates: ["wa", "wo"], id: 45 },
        "ga": { self: "ガ", translation: "ga", falseStates: ["gi", "gu", "ge"], id: 46 },
        "gi": { self: "ギ", translation: "gi", falseStates: ["ga", "gu", "ge"], id: 47 },
        "gu": { self: "グ", translation: "gu", falseStates: ["ga", "gi", "ge"], id: 48 },
        "ge": { self: "ゲ", translation: "ge", falseStates: ["ga", "gi", "gu"], id: 49 },
        "go": { self: "ゴ", translation: "go", falseStates: ["ga", "gi", "gu"], id: 50 },
        "za": { self: "ザ", translation: "za", falseStates: ["ji", "zu", "ze"], id: 51 },
        "ji": { self: "ジ", translation: "ji", falseStates: ["za", "zu", "ze"], id: 52 },
        "zu": { self: "ズ", translation: "zu", falseStates: ["za", "ji", "ze"], id: 53 },
        "ze": { self: "ゼ", translation: "ze", falseStates: ["za", "ji", "zu"], id: 54 },
        "zo": { self: "ゾ", translation: "zo", falseStates: ["za", "ji", "zu"], id: 55 },
        "da": { self: "ダ", translation: "da", falseStates: ["di", "du", "de"], id: 56 },
        "di": { self: "ヂ", translation: "di", falseStates: ["da", "du", "de"], id: 57 },
        "du": { self: "ヅ", translation: "du", falseStates: ["da", "di", "de"], id: 58 },
        "de": { self: "デ", translation: "de", falseStates: ["da", "di", "du"], id: 59 },
        "do": { self: "ド", translation: "do", falseStates: ["da", "di", "du"], id: 60 },
        "ba": { self: "バ", translation: "ba", falseStates: ["bi", "bu", "be"], id: 61 },
        "bi": { self: "ビ", translation: "bi", falseStates: ["ba", "bu", "be"], id: 62 },
        "bu": { self: "ブ", translation: "bu", falseStates: ["ba", "bi", "be"], id: 63 },
        "be": { self: "ベ", translation: "be", falseStates: ["ba", "bi", "bu"], id: 64 },
        "bo": { self: "ボ", translation: "bo", falseStates: ["ba", "bi", "bu"], id: 65 },
        "pa": { self: "パ", translation: "pa", falseStates: ["pi", "pu", "pe"], id: 66 },
        "pi": { self: "ピ", translation: "pi", falseStates: ["pa", "pu", "pe"], id: 67 },
        "pu": { self: "プ", translation: "pu", falseStates: ["pa", "pi", "pe"], id: 68 },
        "pe": { self: "ペ", translation: "pe", falseStates: ["pa", "pi", "pu"], id: 69 },
        "po": { self: "ポ", translation: "po", falseStates: ["pa", "pi", "pu"], id: 70 }
      }
    }
  }


export default Words;